server:
  port: 8081

eureka:
  instance: 
    hostname: localhost
    port: 9000
  client:
    register-with-eureka: true
    fetch-registry: false
    serviceUrl:
      default-zone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
    server:
      wait-time-in-ms-when-sync-empty: 3000 
